# -*- coding: utf-8 -*-
"""AI Semantic Search

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14d8H45WNYw2D5HhtUFNNCEfzKYa7UFnE
"""

!pip install sentence-transformers pinecone-client -q

import pandas as pd

#import os
#os.getcwd()

#from google.colab import files
#upload = files.upload()

data = pd.read_csv("/content/questions.csv")
data.head()

len(data)

data[data['is_duplicate']==1].head()

import pinecone
pinecone.init(api_key='f71a840e-738c-4aa6-8f68-c04b42c256b4', environment='us-west1-gcp-free')

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-mpnet-base-v2',device='cuda')

embeding = model.encode("This is sentence", device='cpu')
len(embeding)

pinecone.create_index(name='question-search', dimension=768)

index = pinecone.Index('question-search')

# [(id,vector,metadata)]

question_list = []
for i,row in data.iterrows():
  question_list.append(
      (
        str(row['id']),
        model.encode(row['question1'], device='cpu').tolist(),
        {
            'is_duplicate': int(row['is_duplicate']),
            'question1': row['question1']
        }
      )
  )
  if len(question_list)==50 or len(question_list)==len(data):
    index.upsert(vectors=question_list)
    question_list = []

query = "How do I prepare for civil service?"
xq = model.encode([query], device='cpu').tolist()
result = index.query(xq, top_k=2, includeMetadata=True)
result

query = "How to levergae internet for business"
xq = model.encode([query], device='cpu').tolist()
result = index.query(xq, top_k=2, includeMetadata=True)
result